server:
    port: 80

spring:
    thymeleaf: 
        prefix: classpath:templates/
        suffix: .html
        cache: false

    datasource:
        url: jdbc:mariadb://35.184.75.127:3306/todolist
        driver-class-name: org.mariadb.jdbc.Driver
        username: minman
        password: Tlqkf!@
    
    jpa:
        open-in-view: false
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update

        

